
# List all clients known to your APIs
clients:
  - id: client-A
    name: Alice's app
    secret: 577067ae-c2e1-11e5-bf25-9f5314291cbe
    # you can list the scopes this clients is allowed to request
    scopes:
      - profile
      - post_tweets

  - id: client-B
    name: Bob's app
    secret: 95b6efe2-c2e1-11e5-ba38-c724a3fd4517
    scope:
      - profile
      - post_tweets
      - read_dm
